### PR TITLE
Feedback 20231205

### PR DESCRIPTION
**Pull request by alexandercyu**
Made changes according to feedback from meeting
- Moved Connect/Login button to top right
- Changed text to reference signing up for waitlist
- Shortened title
- Decreased opacity on sign up area background

### CODE REVIEW

**Review by mishaschwartz — CHANGES_REQUESTED** [review]
Please build this locally and view the changes:

- background is now missing (text is almost unreadable now)
- remove "for information on getting an account". We're not providing information, we just want them to sign up

**Comment by alexandercyu** [comment]
- Changed the text.
- The background should not be missing.  Nothing was changed.  I will look into this.

**Comment by mishaschwartz** [comment]
> The background should not be missing. Nothing was changed. I will look into this.

I tried it in a different browser and it looks good. Sorry, it was probably just a caching issue on my side

**Review by mishaschwartz — APPROVED** [review]
This is good for now.

I've created a few Issues to be addressed later but they do not need to be fixed for this PR

**Pull request merged**
